In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Jo\Documents\Forage BCG 10K Analysis.csv")

Profitability Metrics:

In [3]:
df['Net Margin (%)'] = df['Net Income'] / df['Total Revenue'] * 100
df['ROA (%)'] = df['Net Income'] / df['Total Assets'] * 100

Leverage and Liquidity Ratios:

In [4]:
df['Asset-to-Liability Ratio'] = df['Total Assets']/df['Total Liabilities']
df['Operating Cash Flow Ratio'] = df['Cash Flow from Operating Activities']/df['Total Liabilities']

Efficiency Metrics:

In [5]:
df['Asset Turnover'] = df['Total Revenue'] / df['Total Assets']
df['Cash Flow Margin (%)'] = df['Cash Flow from Operating Activities']/df['Total Revenue'] * 100

Growth Measures:

In [6]:
df['Revenue Growth (%)'] = df.groupby(['Company'])['Total Revenue'].pct_change() * 100
df['Net Income Growth (%)'] = df.groupby(['Company'])['Net Income'].pct_change() * 100
df['Operating Cash Flow Growth(%)'] = df.groupby(['Company'])['Cash Flow from Operating Activities'].pct_change() * 100
df['Margin Expansion (pp)'] = df.groupby('Company')['Net Margin (%)'].diff()

In [7]:
rev_pivot_df = df.pivot(index = 'Company', columns = 'Year', values = 'Total Revenue')
rev_cagr = ((rev_pivot_df[2025] / rev_pivot_df[2023])**(1/2) - 1) * 100

inc_pivot_df = df.pivot(index = 'Company', columns = 'Year', values = 'Net Income')
inc_cagr = ((inc_pivot_df[2025] / inc_pivot_df[2023])**(1/2) - 1) * 100

In [8]:
df['Revenue CAGR (%)'] = df['Company'].map(rev_cagr)
df['Net Income CAGR (%)'] = df['Company'].map(inc_cagr)

df = df.sort_values(by=['Company', 'Year'])
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Net Margin (%),ROA (%),Asset-to-Liability Ratio,Operating Cash Flow Ratio,Asset Turnover,Cash Flow Margin (%),Revenue Growth (%),Net Income Growth (%),Operating Cash Flow Growth(%),Margin Expansion (pp),Revenue CAGR (%),Net Income CAGR (%)
2,Apple,2023,383285,96995,352583,290437,110543,25.306234,27.509835,1.213974,0.380609,1.087077,28.840941,NaN,NaN,NaN,NaN,4.200494,7.461705
5,Apple,2024,391035,93736,364980,308030,118254,23.971256,25.682503,1.184885,0.383904,1.071387,30.241283,2.021994,-3.359967,6.975566,-1.334978,4.200494,7.461705
8,Apple,2025,416161,112010,359241,285508,111482,26.915064,31.179626,1.258252,0.390469,1.158445,26.788190,6.425512,19.495178,-5.726656,2.943808,4.200494,7.461705
0,Microsoft,2023,211915,72361,411976,205753,87582,34.146238,17.564373,2.002284,0.425666,0.514387,41.328835,NaN,NaN,NaN,NaN,15.300469,18.628723
3,Microsoft,2024,245122,88136,512163,243686,118548,35.955973,17.208584,2.101733,0.486479,0.478602,48.362856,15.669962,21.800417,35.356580,1.809735,15.300469,18.628723
6,Microsoft,2025,281724,101832,619003,275524,136162,36.146015,16.450970,2.246639,0.494193,0.455125,48.331701,14.932156,15.539621,14.858117,0.190042,15.300469,18.628723
1,Tesla,2023,96773,14974,106618,43009,13256,15.473324,14.044533,2.478970,0.308215,0.907661,13.698036,NaN,NaN,NaN,NaN,-1.010552,-49.260840
4,Tesla,2024,97690,7153,122070,48390,14923,7.322141,5.859753,2.522629,0.308390,0.800279,15.275873,0.947578,-52.230533,12.575438,-8.151183,-1.010552,-49.260840
7,Tesla,2025,94827,3855,137806,54941,14747,4.065298,2.797411,2.508254,0.268415,0.688120,15.551478,-2.930699,-46.106529,-1.179388,-3.256844,-1.010552,-49.260840

# BCG 10-K Financial Analysis Report (2023–2025)
## Performance Summary

In [9]:
cagr_summary = pd.DataFrame({
    'Revenue CAGR %': rev_cagr,
    'Net Income CAGR %': inc_cagr
})

cagr_summary.round(2)

           Revenue CAGR %  Net Income CAGR %
Company
Apple                4.20               7.46
Microsoft           15.30              18.63
Tesla               -1.01             -49.26

### Microsoft
* Not only does Microsoft have the highest revenue CAGR, but its net income CAGR shows *net income growth outpaced revenue growth*. This means that, over the past three years, Microsoft has become **more operationally efficient**, becoming more profitable for each dollar of revenue it earns.
### Apple
* Similarly, although at more modest values, Apple also continues to optimize its bottom line. Apple maintains its presence as a mature market leader.
### Tesla
* On the other hand, Tesla has faced a few difficult years. Revenue growth has flatlined, and *net income has halved* year over year. While Tesla has maintained sales volume, **increasing COGS or operating expenses** has been eating into its margins.

## Health and Solvency
### Asset-to-Liability Ratio

In [10]:
solvency_trend = df.pivot(index = 'Year', columns = 'Company', values = 'Asset-to-Liability Ratio')
solvency_trend.round(2)

Company  Apple  Microsoft  Tesla
Year
2023      1.21       2.00   2.48
2024      1.18       2.10   2.52
2025      1.26       2.25   2.51

* Tesla maintained a very high (safe) ratio, with low debt compared to its assets. Microsoft has also been increasing its ratio, from 2.00 in 2023 up to 2.25 in 2025. On the other hand, Apple has much higher debt leverage, with a ratio much closer to 1.

### Cash Flow Margin

In [11]:
cfmargin_trend = df.pivot(index = 'Year', columns = 'Company', values = 'Cash Flow Margin (%)')
cfmargin_trend.round(2)

Company  Apple  Microsoft  Tesla
Year
2023     28.84      41.33  13.70
2024     30.24      48.36  15.28
2025     26.79      48.33  15.55

* Microsoft is incredibly good at converting revenue directly into operating cash flow, with nearly 50% cash flow margins. On the other hand, Tesla may struggle with liquidity.

## Conclusions
* Microsoft continues to be a **high-growth firm**, navigating its technological transitions incredibly well.
* Apple remains a solid organization capable of extracting value from a mature market.
* Tesla has struggled in the past few years. It *needs a new catalyst* to extract itself. **Monitor closely**.